import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import {
  Phone, PhoneCall, PhoneOff, PhoneIncoming, PhoneMissed,
  Ticket, Send, Clock, User, MapPin, AlertTriangle, CheckCircle,
  Plus, Mic, MicOff, Volume2, Headphones, FileText, Loader2
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { format } from "date-fns";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";

const CallOperatorConsole = () => {
  const [activeCall, setActiveCall] = useState<any>(null);
  const [isMuted, setIsMuted] = useState(false);
  const [callDuration, setCallDuration] = useState(0);
  const [isTicketDialogOpen, setIsTicketDialogOpen] = useState(false);
  const [isDispatchDialogOpen, setIsDispatchDialogOpen] = useState(false);
  const [operatorStatus, setOperatorStatus] = useState<'available' | 'on-call' | 'wrap-up' | 'break'>('available');
  const queryClient = useQueryClient();

  // Timer for active call
  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (activeCall) {
      interval = setInterval(() => {
        setCallDuration(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [activeCall]);

  // Fetch calls
  const { data: calls = [] } = useQuery({
    queryKey: ['operator-calls'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('calls')
        .select('*, assigned_operator:profiles(full_name)')
        .order('started_at', { ascending: false })
        .limit(20);
      if (error) throw error;
      return data || [];
    },
    refetchInterval: 5000
  });

  // Fetch tickets
  const { data: tickets = [] } = useQuery({
    queryKey: ['operator-tickets'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('communication_tickets')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(20);
      if (error) throw error;
      return data || [];
    }
  });

  // Real-time subscriptions for live updates
  useEffect(() => {
    const callsChannel = supabase
      .channel('operator-calls-realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'calls' }, () => {
        queryClient.invalidateQueries({ queryKey: ['operator-calls'] });
      })
      .subscribe();

    const ticketsChannel = supabase
      .channel('operator-tickets-realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'communication_tickets' }, () => {
        queryClient.invalidateQueries({ queryKey: ['operator-tickets'] });
      })
      .subscribe();

    const dispatchChannel = supabase
      .channel('operator-dispatch-realtime')
      .on('postgres_changes', { event: '*', schema: 'public', table: 'dispatch_requests' }, () => {
        toast.info("New dispatch activity");
      })
      .subscribe();

    return () => {
      supabase.removeChannel(callsChannel);
      supabase.removeChannel(ticketsChannel);
      supabase.removeChannel(dispatchChannel);
    };
  }, [queryClient]);

  // Create ticket mutation
  const createTicketMutation = useMutation({
    mutationFn: async (ticketData: any) => {
      const { error } = await supabase
        .from('communication_tickets')
        .insert({
          ...ticketData,
          ticket_number: `TKT-${Date.now()}`,
          status: 'open',
          channel: 'phone'
        });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['operator-tickets'] });
      toast.success("Ticket created successfully");
      setIsTicketDialogOpen(false);
    },
    onError: () => toast.error("Failed to create ticket")
  });

  // Create dispatch mutation
  const createDispatchMutation = useMutation({
    mutationFn: async (dispatchData: any) => {
      const { data: { user } } = await supabase.auth.getUser();
      
      // First create a ticket (ticket_number is auto-generated by trigger)
      const { data: ticket, error: ticketError } = await supabase
        .from('communication_tickets')
        .insert([{
          ticket_number: `TKT-${Date.now()}`,
          subject: dispatchData.description,
          message: dispatchData.description,
          sender_contact: 'Operator Console',
          status: 'new' as const,
          channel: 'phone' as const,
          priority: dispatchData.priority
        }])
        .select()
        .single();
      
      if (ticketError) throw ticketError;

      const { error } = await supabase
        .from('dispatch_requests')
        .insert([{
          dispatch_type: dispatchData.dispatch_type,
          description: dispatchData.description,
          location: dispatchData.location,
          priority: dispatchData.priority,
          gps_lat: dispatchData.gps_lat,
          gps_lng: dispatchData.gps_lng,
          request_number: `DISP-${Date.now()}`,
          ticket_id: ticket.id,
          requested_by: user?.id,
          status: 'pending'
        }]);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success("Dispatch request created");
      setIsDispatchDialogOpen(false);
    },
    onError: () => toast.error("Failed to create dispatch")
  });

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const handleAnswerCall = (call: any) => {
    setActiveCall(call);
    setCallDuration(0);
    setOperatorStatus('on-call');
    toast.info(`Connected to ${call.caller_number}`);
  };

  const handleEndCall = () => {
    setActiveCall(null);
    setCallDuration(0);
    setOperatorStatus('wrap-up');
    toast.info("Call ended");
    setTimeout(() => setOperatorStatus('available'), 30000); // 30s wrap-up
  };

  const handleCreateTicket = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    createTicketMutation.mutate({
      subject: formData.get('subject'),
      message: formData.get('message'),
      sender_contact: formData.get('caller') || activeCall?.caller_number,
      sender_name: formData.get('caller_name'),
      priority: formData.get('priority'),
      linked_call_id: activeCall?.id
    });
  };

  const handleCreateDispatch = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    createDispatchMutation.mutate({
      dispatch_type: formData.get('type'),
      description: formData.get('description'),
      location: formData.get('location'),
      priority: formData.get('priority'),
      gps_lat: -1.2921,
      gps_lng: 36.8219
    });
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'available': return 'bg-alert-normal';
      case 'on-call': return 'bg-alert-critical';
      case 'wrap-up': return 'bg-alert-caution';
      case 'break': return 'bg-muted';
      default: return 'bg-muted';
    }
  };

  const incomingCalls = [
    { id: 1, caller_number: '+254722111222', caller_name: 'John Mwangi', queue_time: 15, priority: 'high' },
    { id: 2, caller_number: '+254733444555', caller_name: 'Unknown', queue_time: 8, priority: 'normal' },
  ];

  return (
    <div className="space-y-4">
      {/* Operator Status Bar */}
      <Card className="bg-gradient-to-r from-primary/10 to-primary/5 border-primary/20">
        <CardContent className="p-4">
          <div className="flex items-center justify-between flex-wrap gap-4">
            <div className="flex items-center gap-4">
              <Avatar className="h-10 w-10">
                <AvatarFallback className="bg-primary/20">OP</AvatarFallback>
              </Avatar>
              <div>
                <p className="font-medium">Operator Console</p>
                <div className="flex items-center gap-2">
                  <Badge className={getStatusColor(operatorStatus)}>
                    {operatorStatus.charAt(0).toUpperCase() + operatorStatus.slice(1).replace('-', ' ')}
                  </Badge>
                  <span className="text-xs text-muted-foreground">
                    Shift: 08:00 - 20:00
                  </span>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <Select value={operatorStatus} onValueChange={(v: any) => setOperatorStatus(v)}>
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="available">Available</SelectItem>
                  <SelectItem value="wrap-up">Wrap-up</SelectItem>
                  <SelectItem value="break">Break</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        {/* Left Panel - Call Queue & Active Call */}
        <div className="lg:col-span-2 space-y-4">
          {/* Active Call Panel */}
          {activeCall ? (
            <Card className="border-alert-critical/50 bg-alert-critical/5">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <PhoneCall className="w-4 h-4 text-alert-critical animate-pulse" />
                  Active Call
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <p className="text-2xl font-bold">{activeCall.caller_number}</p>
                    <p className="text-sm text-muted-foreground">{activeCall.caller_name || 'Unknown Caller'}</p>
                  </div>
                  <div className="text-right">
                    <p className="text-3xl font-mono font-bold text-alert-critical">
                      {formatDuration(callDuration)}
                    </p>
                  </div>
                </div>
                
                <div className="flex items-center justify-center gap-4">
                  <Button
                    size="lg"
                    variant={isMuted ? 'destructive' : 'outline'}
                    onClick={() => setIsMuted(!isMuted)}
                  >
                    {isMuted ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
                  </Button>
                  <Button
                    size="lg"
                    variant="destructive"
                    className="px-8"
                    onClick={handleEndCall}
                  >
                    <PhoneOff className="w-5 h-5 mr-2" />
                    End Call
                  </Button>
                  <Button size="lg" variant="outline">
                    <Volume2 className="w-5 h-5" />
                  </Button>
                </div>

                <div className="flex gap-2 mt-4">
                  <Dialog open={isTicketDialogOpen} onOpenChange={setIsTicketDialogOpen}>
                    <DialogTrigger asChild>
                      <Button variant="outline" className="flex-1 gap-2">
                        <Ticket className="w-4 h-4" />
                        Create Ticket
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Create Support Ticket</DialogTitle>
                      </DialogHeader>
                      <form onSubmit={handleCreateTicket} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                          <div className="space-y-2">
                            <Label>Caller Number</Label>
                            <Input name="caller" defaultValue={activeCall?.caller_number} />
                          </div>
                          <div className="space-y-2">
                            <Label>Caller Name</Label>
                            <Input name="caller_name" placeholder="Name" />
                          </div>
                        </div>
                        <div className="space-y-2">
                          <Label>Subject</Label>
                          <Input name="subject" placeholder="Brief description" required />
                        </div>
                        <div className="space-y-2">
                          <Label>Priority</Label>
                          <Select name="priority" defaultValue="normal">
                            <SelectTrigger>
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="critical">Critical</SelectItem>
                              <SelectItem value="high">High</SelectItem>
                              <SelectItem value="normal">Normal</SelectItem>
                              <SelectItem value="low">Low</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>Message/Notes</Label>
                          <Textarea name="message" placeholder="Details..." rows={4} required />
                        </div>
                        <Button type="submit" className="w-full" disabled={createTicketMutation.isPending}>
                          {createTicketMutation.isPending ? (
                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          ) : (
                            <Ticket className="w-4 h-4 mr-2" />
                          )}
                          Create Ticket
                        </Button>
                      </form>
                    </DialogContent>
                  </Dialog>

                  <Dialog open={isDispatchDialogOpen} onOpenChange={setIsDispatchDialogOpen}>
                    <DialogTrigger asChild>
                      <Button variant="outline" className="flex-1 gap-2">
                        <Send className="w-4 h-4" />
                        Dispatch
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Create Dispatch Request</DialogTitle>
                      </DialogHeader>
                      <form onSubmit={handleCreateDispatch} className="space-y-4">
                        <div className="space-y-2">
                          <Label>Dispatch Type</Label>
                          <Select name="type" required>
                            <SelectTrigger>
                              <SelectValue placeholder="Select type" />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="alarm_response">Alarm Response</SelectItem>
                              <SelectItem value="patrol_backup">Patrol Backup</SelectItem>
                              <SelectItem value="emergency">Emergency</SelectItem>
                              <SelectItem value="welfare_check">Welfare Check</SelectItem>
                              <SelectItem value="technical">Technical Support</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>Priority</Label>
                          <Select name="priority" defaultValue="normal">
                            <SelectTrigger>
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="critical">Critical</SelectItem>
                              <SelectItem value="high">High</SelectItem>
                              <SelectItem value="normal">Normal</SelectItem>
                              <SelectItem value="low">Low</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-2">
                          <Label>Location</Label>
                          <Input name="location" placeholder="Address or site name" required />
                        </div>
                        <div className="space-y-2">
                          <Label>Description</Label>
                          <Textarea name="description" placeholder="Situation details..." rows={4} required />
                        </div>
                        <Button type="submit" className="w-full" disabled={createDispatchMutation.isPending}>
                          {createDispatchMutation.isPending ? (
                            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          ) : (
                            <Send className="w-4 h-4 mr-2" />
                          )}
                          Create Dispatch
                        </Button>
                      </form>
                    </DialogContent>
                  </Dialog>
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardContent className="p-8 text-center text-muted-foreground">
                <Headphones className="w-16 h-16 mx-auto mb-4 opacity-30" />
                <p className="text-lg font-medium">No Active Call</p>
                <p className="text-sm">Answer an incoming call to begin</p>
              </CardContent>
            </Card>
          )}

          {/* Incoming Calls Queue */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm flex items-center gap-2">
                <PhoneIncoming className="w-4 h-4" />
                Incoming Calls
                <Badge variant="secondary">{incomingCalls.length}</Badge>
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-2">
                {incomingCalls.map((call) => (
                  <div key={call.id} className="flex items-center justify-between p-3 bg-muted/50 rounded-lg border-l-4 border-l-alert-caution">
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-full bg-alert-caution/20">
                        <Phone className="w-4 h-4 text-alert-caution animate-pulse" />
                      </div>
                      <div>
                        <p className="font-medium">{call.caller_number}</p>
                        <p className="text-xs text-muted-foreground">{call.caller_name}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <div className="text-right">
                        <Badge variant={call.priority === 'high' ? 'destructive' : 'secondary'}>
                          {call.priority}
                        </Badge>
                        <p className="text-xs text-muted-foreground mt-1">
                          Waiting {call.queue_time}s
                        </p>
                      </div>
                      <Button
                        size="sm"
                        className="bg-alert-normal hover:bg-alert-normal/90"
                        onClick={() => handleAnswerCall(call)}
                        disabled={!!activeCall}
                      >
                        <Phone className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                ))}
                {incomingCalls.length === 0 && (
                  <div className="text-center py-6 text-muted-foreground">
                    <Phone className="w-8 h-8 mx-auto mb-2 opacity-30" />
                    <p className="text-sm">No incoming calls</p>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right Panel - Tickets & History */}
        <div className="space-y-4">
          {/* Quick Actions */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Quick Actions</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              <Dialog open={isTicketDialogOpen} onOpenChange={setIsTicketDialogOpen}>
                <DialogTrigger asChild>
                  <Button variant="outline" className="w-full justify-start gap-2">
                    <Plus className="w-4 h-4" />
                    New Ticket
                  </Button>
                </DialogTrigger>
              </Dialog>
              <Dialog open={isDispatchDialogOpen} onOpenChange={setIsDispatchDialogOpen}>
                <DialogTrigger asChild>
                  <Button variant="outline" className="w-full justify-start gap-2">
                    <Send className="w-4 h-4" />
                    New Dispatch
                  </Button>
                </DialogTrigger>
              </Dialog>
            </CardContent>
          </Card>

          {/* Recent Tickets */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm flex items-center gap-2">
                <Ticket className="w-4 h-4" />
                Recent Tickets
              </CardTitle>
            </CardHeader>
            <CardContent>
              <ScrollArea className="h-[300px]">
                <div className="space-y-2">
                  {tickets.length === 0 ? (
                    <div className="text-center py-6 text-muted-foreground">
                      <FileText className="w-8 h-8 mx-auto mb-2 opacity-30" />
                      <p className="text-sm">No tickets yet</p>
                    </div>
                  ) : (
                    tickets.slice(0, 10).map((ticket: any) => (
                      <div key={ticket.id} className="p-3 bg-muted/50 rounded-lg">
                        <div className="flex items-center justify-between mb-1">
                          <span className="text-xs font-medium">{ticket.ticket_number}</span>
                          <Badge variant={ticket.status === 'open' ? 'destructive' : 'secondary'} className="text-xs">
                            {ticket.status}
                          </Badge>
                        </div>
                        <p className="text-sm font-medium truncate">{ticket.subject}</p>
                        <p className="text-xs text-muted-foreground">{ticket.sender_contact}</p>
                      </div>
                    ))
                  )}
                </div>
              </ScrollArea>
            </CardContent>
          </Card>

          {/* Call Stats */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm">Today's Stats</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <p className="text-2xl font-bold text-alert-normal">{calls.filter((c: any) => c.status === 'completed').length}</p>
                  <p className="text-xs text-muted-foreground">Answered</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <p className="text-2xl font-bold text-alert-critical">{calls.filter((c: any) => c.status === 'missed').length}</p>
                  <p className="text-xs text-muted-foreground">Missed</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <p className="text-2xl font-bold">{tickets.filter((t: any) => t.status === 'open').length}</p>
                  <p className="text-xs text-muted-foreground">Open Tickets</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-lg text-center">
                  <p className="text-2xl font-bold">4:32</p>
                  <p className="text-xs text-muted-foreground">Avg Handle</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default CallOperatorConsole;
