import { useState } from "react";
import { Button } from "@/components/ui/button";
import { AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

interface SOSButtonProps {
  vehicleId: string;
}

const SOSButton = ({ vehicleId }: SOSButtonProps) => {
  const { user } = useAuth();
  const [triggering, setTriggering] = useState(false);

  const handleSOS = async () => {
    if (!navigator.geolocation) {
      toast.error("Geolocation not supported");
      return;
    }

    setTriggering(true);

    navigator.geolocation.getCurrentPosition(
      async (position) => {
        try {
          const { error } = await supabase.from("sos_alerts").insert([{
            vehicle_id: vehicleId,
            officer_id: user?.id,
            gps_lat: position.coords.latitude,
            gps_lng: position.coords.longitude,
            status: "active",
            alert_number: '', // Will be auto-generated by trigger
          }] as any);

          if (error) throw error;

          // Update vehicle status
          await supabase
            .from("vehicles")
            .update({ status: "emergency" })
            .eq("id", vehicleId);

          toast.error("🚨 SOS ALERT SENT - Help is on the way", {
            duration: 10000,
          });
        } catch (error: any) {
          console.error("SOS error:", error);
          toast.error("Failed to send SOS alert");
        } finally {
          setTriggering(false);
        }
      },
      (error) => {
        console.error("Geolocation error:", error);
        toast.error("Failed to get GPS location");
        setTriggering(false);
      },
      { enableHighAccuracy: true }
    );
  };

  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button
          variant="destructive"
          size="lg"
          className="w-full lg:w-auto lg:fixed lg:bottom-6 lg:right-6 lg:z-50 gap-2 text-lg font-bold animate-pulse hover:animate-none"
          disabled={triggering}
        >
          <AlertTriangle className="w-6 h-6" />
          EMERGENCY SOS
        </Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle className="text-destructive">🚨 Emergency SOS Alert</AlertDialogTitle>
          <AlertDialogDescription>
            This will immediately notify the control room of an emergency at your location.
            Your GPS coordinates will be sent along with vehicle and officer information.
            <br />
            <br />
            <strong>Only press this button if you are in a genuine emergency situation.</strong>
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel>Cancel</AlertDialogCancel>
          <AlertDialogAction
            onClick={handleSOS}
            className="bg-destructive hover:bg-destructive/90"
          >
            SEND SOS ALERT
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
};

export default SOSButton;
