import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { logAudit } from "@/utils/auditLog";

interface ControlRoomAssignmentsProps {
  vehicles: any[];
}

const patrolTypes = ["random", "scheduled", "alarm_response", "escort"];
const priorities = ["normal", "high", "urgent"];

const ControlRoomAssignments = ({ vehicles }: ControlRoomAssignmentsProps) => {
  const { user } = useAuth();
  const [formData, setFormData] = useState({
    vehicle_id: "",
    site_name: "",
    client_name: "",
    patrol_type: "scheduled",
    priority: "normal",
    route_name: "",
    notes: "",
  });
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.vehicle_id || !formData.site_name) {
      toast.error("Please select vehicle and site");
      return;
    }

    setSubmitting(true);

    try {
      const vehicle = vehicles.find((v) => v.id === formData.vehicle_id);

      const { error: patrolError } = await supabase.from("mobile_patrols").insert([{
        vehicle_id: formData.vehicle_id,
        officer_id: vehicle?.current_officer_id,
        site_name: formData.site_name,
        client_name: formData.client_name,
        patrol_type: formData.patrol_type,
        priority: formData.priority,
        route_name: formData.route_name,
        start_time: new Date().toISOString(),
        notes: formData.notes,
        created_by: user?.id,
        patrol_id: '', // Will be auto-generated by trigger
      }] as any);

      if (patrolError) throw patrolError;

      // Send message to vehicle
      await supabase.from("mdt_messages").insert([{
        vehicle_id: formData.vehicle_id,
        sent_by: user?.id,
        message_type: "patrol_order",
        message: `New ${formData.patrol_type} patrol assigned: ${formData.site_name}`,
        priority: formData.priority,
      }] as any);

      // Log to audit trail
      await logAudit({
        module: "patrol_assignments",
        action: "create_patrol",
        changes: {
          vehicle_id: formData.vehicle_id,
          site_name: formData.site_name,
          patrol_type: formData.patrol_type,
          priority: formData.priority,
        },
      });

      toast.success("Patrol assigned successfully");
      setFormData({
        vehicle_id: "",
        site_name: "",
        client_name: "",
        patrol_type: "scheduled",
        priority: "normal",
        route_name: "",
        notes: "",
      });
    } catch (error: any) {
      console.error("Error creating assignment:", error);
      toast.error("Failed to create assignment");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Card className="p-6">
      <h2 className="text-xl font-bold mb-4">Create Patrol Assignment</h2>
      <form onSubmit={handleSubmit} className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <Label>Vehicle *</Label>
            <Select
              value={formData.vehicle_id}
              onValueChange={(value) => setFormData({ ...formData, vehicle_id: value })}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select vehicle" />
              </SelectTrigger>
              <SelectContent>
                {vehicles
                  .filter((v) => v.status === "available")
                  .map((vehicle) => (
                    <SelectItem key={vehicle.id} value={vehicle.id}>
                      {vehicle.vehicle_id} - {vehicle.vehicle_type}
                    </SelectItem>
                  ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label>Patrol Type</Label>
            <Select
              value={formData.patrol_type}
              onValueChange={(value) => setFormData({ ...formData, patrol_type: value })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {patrolTypes.map((type) => (
                  <SelectItem key={type} value={type}>
                    {type.replace("_", " ").toUpperCase()}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label>Site Name *</Label>
            <Input
              value={formData.site_name}
              onChange={(e) => setFormData({ ...formData, site_name: e.target.value })}
              placeholder="Enter site name"
            />
          </div>

          <div>
            <Label>Client Name</Label>
            <Input
              value={formData.client_name}
              onChange={(e) => setFormData({ ...formData, client_name: e.target.value })}
              placeholder="Enter client name"
            />
          </div>

          <div>
            <Label>Priority</Label>
            <Select
              value={formData.priority}
              onValueChange={(value) => setFormData({ ...formData, priority: value })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {priorities.map((priority) => (
                  <SelectItem key={priority} value={priority}>
                    {priority.toUpperCase()}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div>
            <Label>Route Name</Label>
            <Input
              value={formData.route_name}
              onChange={(e) => setFormData({ ...formData, route_name: e.target.value })}
              placeholder="Enter route name"
            />
          </div>
        </div>

        <div>
          <Label>Notes</Label>
          <Textarea
            value={formData.notes}
            onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
            placeholder="Additional instructions..."
            rows={3}
          />
        </div>

        <Button type="submit" disabled={submitting} className="w-full">
          {submitting ? "Creating..." : "Dispatch Patrol"}
        </Button>
      </form>
    </Card>
  );
};

export default ControlRoomAssignments;
