import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/components/ui/use-toast";
import { PlusCircle } from "lucide-react";
import { OperationalContextFields, emptyOperationalContext, OperationalContextValue } from "@/components/shared/OperationalContextFields";
import { appendContext, uploadContextAttachments } from "@/components/shared/operationalContext";

interface AdvisoryCreateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

const AdvisoryCreateDialog = ({ open, onOpenChange, onSuccess }: AdvisoryCreateDialogProps) => {
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [ctx, setCtx] = useState<OperationalContextValue>(emptyOperationalContext());
  const [formData, setFormData] = useState({
    category: "Traffic",
    sub_category: "",
    title: "",
    description: "",
    severity: "NORMAL",
    location_lat: "",
    location_lon: "",
    proximate_poi: "",
    recommended_action: ""
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const { data: { user } } = await supabase.auth.getUser();
      
      const lat = formData.location_lat ? parseFloat(formData.location_lat) : (ctx.geo?.lat ?? null);
      const lon = formData.location_lon ? parseFloat(formData.location_lon) : (ctx.geo?.lng ?? null);
      const { data: inserted, error } = await supabase
        .from("strategic_advisories")
        .insert([{
          incident_id: '', // Auto-generated by trigger
          category: formData.category,
          sub_category: formData.sub_category,
          title: formData.title,
          description: appendContext(formData.description, ctx),
          severity: formData.severity,
          location_lat: lat,
          location_lon: lon,
          proximate_poi: formData.proximate_poi,
          recommended_action: formData.recommended_action,
          created_by: user?.id,
          location_scope_hierarchy: ["Global", "Africa", "Kenya", "Nairobi"]
        }])
        .select('id')
        .single();

      if (error) throw error;
      if (inserted?.id && ctx.attachments.length) {
        await uploadContextAttachments('strategic-advisory', inserted.id, ctx.attachments);
      }

      toast({ title: "Advisory Created", description: "New strategic advisory has been created successfully." });
      onSuccess();
      onOpenChange(false);
      
      // Reset form
      setFormData({
        category: "Traffic",
        sub_category: "",
        title: "",
        description: "",
        severity: "NORMAL",
        location_lat: "",
        location_lon: "",
        proximate_poi: "",
        recommended_action: ""
      });
    } catch (error: any) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <PlusCircle className="w-5 h-5 text-primary" />
            Create New Strategic Advisory
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 py-4">
          <div className="grid grid-cols-2 gap-4">
            {/* Category */}
            <div>
              <Label>Category *</Label>
              <Select
                value={formData.category}
                onValueChange={(value) => setFormData({ ...formData, category: value })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Traffic">Traffic</SelectItem>
                  <SelectItem value="Protest">Protest</SelectItem>
                  <SelectItem value="Terror">Terror</SelectItem>
                  <SelectItem value="Weather">Weather</SelectItem>
                  <SelectItem value="Crime">Crime</SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Sub-Category */}
            <div>
              <Label>Sub-Category</Label>
              <Input
                placeholder="e.g., Congestion, Gathering"
                value={formData.sub_category}
                onChange={(e) => setFormData({ ...formData, sub_category: e.target.value })}
              />
            </div>
          </div>

          {/* Title */}
          <div>
            <Label>Title *</Label>
            <Input
              placeholder="Brief incident title"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              required
            />
          </div>

          {/* Description */}
          <div>
            <Label>Description *</Label>
            <Textarea
              placeholder="Detailed description of the incident"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              required
              className="min-h-[100px]"
            />
          </div>

          {/* Severity */}
          <div>
            <Label>Severity *</Label>
            <Select
              value={formData.severity}
              onValueChange={(value) => setFormData({ ...formData, severity: value })}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="NORMAL">Normal</SelectItem>
                <SelectItem value="CAUTION">Caution</SelectItem>
                <SelectItem value="CRITICAL">Critical</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Location */}
          <div className="grid grid-cols-2 gap-4">
            <div>
              <Label>Latitude</Label>
              <Input
                type="number"
                step="0.000001"
                placeholder="-1.2921"
                value={formData.location_lat}
                onChange={(e) => setFormData({ ...formData, location_lat: e.target.value })}
              />
            </div>
            <div>
              <Label>Longitude</Label>
              <Input
                type="number"
                step="0.000001"
                placeholder="36.8219"
                value={formData.location_lon}
                onChange={(e) => setFormData({ ...formData, location_lon: e.target.value })}
              />
            </div>
          </div>

          {/* POI */}
          <div>
            <Label>Nearby Point of Interest</Label>
            <Input
              placeholder="e.g., Roasters Inn, ABC Place"
              value={formData.proximate_poi}
              onChange={(e) => setFormData({ ...formData, proximate_poi: e.target.value })}
            />
          </div>

          {/* Recommended Action */}
          <div>
            <Label>Recommended Action *</Label>
            <Textarea
              placeholder="What action should be taken?"
              value={formData.recommended_action}
              onChange={(e) => setFormData({ ...formData, recommended_action: e.target.value })}
              required
              className="min-h-[80px]"
            />
          </div>

          <OperationalContextFields value={ctx} onChange={setCtx} />

          {/* Actions */}
          <div className="flex gap-3 pt-4">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)} className="flex-1">
              Cancel
            </Button>
            <Button type="submit" disabled={isSubmitting} className="flex-1">
              Create Advisory
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default AdvisoryCreateDialog;